<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Activity Log Report</title>
    <style>
        body { font-family: sans-serif; color: #333; line-height: 1.5; margin: 0; padding: 20px; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #eee; padding-bottom: 20px; }
        .header h1 { margin: 0 0 10px 0; color: #111; }
        .header p { margin: 0; color: #666; font-size: 14px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 12px; }
        th, td { padding: 8px 10px; border: 1px solid #ddd; text-align: left; }
        th { background-color: #f8f9fa; font-weight: bold; color: #444; }
        .footer { text-align: center; margin-top: 50px; font-size: 12px; color: #888; border-top: 1px solid #eee; padding-top: 20px; }
        @media print { body { padding: 0; } .no-print { display: none; } }
        .btn-print { display: inline-block; padding: 10px 20px; background: #0ea5e9; color: white; text-decoration: none; border-radius: 5px; margin-bottom: 20px; cursor: pointer; border: none; font-size: 14px; }
    </style>
</head>
<body>
    <div class="no-print" style="text-align: right;">
        <button onclick="window.print()" class="btn-print">Print / Save as PDF</button>
    </div>

    <div class="header">
        <h1>Boarding House Management</h1>
        <h2>System Activity Log Report</h2>
        @if($date)
            <p>Filter Date: {{ $date }}</p>
        @else
            <p>Generated on: {{ now()->format('d M Y H:i') }}</p>
        @endif
    </div>

    <table>
        <thead>
            <tr>
                <th width="15%">Timestamp</th>
                <th width="20%">User (Role)</th>
                <th width="15%">Event</th>
                <th width="35%">Description</th>
                <th width="15%">Model</th>
            </tr>
        </thead>
        <tbody>
            @foreach($logs as $log)
                <tr>
                    <td>{{ $log->created_at->format('d M Y H:i:s') }}</td>
                    <td>{{ $log->user->name ?? 'System' }} ({{ $log->user->role ?? '-' }})</td>
                    <td>{{ $log->event }}</td>
                    <td>{{ $log->description }}</td>
                    <td>{{ $log->subject_type ? class_basename($log->subject_type) . ' #' . $log->subject_id : '-' }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by Boarding House Management System on {{ now()->format('d M Y H:i:s') }}
    </div>

    <script>
        window.onload = function() {
            // window.print();
        }
    </script>
</body>
</html>
